spring:
  kafka:
    bootstrap-servers: localhost:9092
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
---
spring:
  profiles: docker-compose
  kafka:
    bootstrap-servers: kafka:9092